### ISSUE TITLE
Integration Filebot

### ISSUE THREAD

**Issue by Majaxx** [4r3/synchro-seedbox#2]
Bonjour , 
se serai pas mal si filebot renommer les films , series avant la synchro ! 
Qu'en pensez vous ?
Cordialement

**Comment by 4r3** [comment]
Bonjour,
actuellement je suis en train de travailler sur un plugin intégré à rutorrent remplissant les mêmes fonctionnalités. Je n’ai donc pas le temps de maintenir le script original. Cependant je garde votre idée pour une version du ultérieure du plugin.
Cordialement
